app:
  client-platform:
    header-name: X-Client-Platform
    web-value: WEB
    android-value: ANDROID
    trusted-web-origins: 
      - http://localhost:5173
      - http://localhost:3000

devices:
  retention:
    archiveAfterDays: 90
    deleteAfterDays: 365
  cleanup:
    cron: "0 30 3 * * *"